spring:
  application:
    name: demo-service
  cloud:
    nacos:
      server-addr: localhost:8848
server:
  port: 8002
#  XXL 配置
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: demo-provider
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999